version: "3.3"

services:
  centos7:
    build:
      context: .
      dockerfile: Dockerfile-centos7
    image: zimbra/zcs-build:centos7
    container_name: centos7
    domainname: test
    env_file:
      - github.env
    hostname: centos7
    volumes:
      - ${REPO_DIR:-.}/DOT-ssh:/DOT-ssh

